// export * from './base-id.interface';
// export * from './base-name.interface';
export * from './category.interface';
export * from './course.interface';
export * from './enrollment.interface';
// export * from './form-table-element.interface';
export * from './navbar-item.interface';
// export * from './play-list.interface';
export * from './play-list-item.interface';
// export * from './play-list-source.interface';
// export * from './role.interface';
export * from './select-item.interface';
export * from './status.interface';
export * from './tag.interface';
// export * from './user.interface';
export * from './utils';
